version: '3.8'

services:

    ## PHP Service
    app:
        platform: linux/x86_64
        image: nhanlh94/php74:1.0
        container_name: app
        restart: always
        tty: true
        environment:
            SERVICE_NAME: app
            SERVICE_TAGS: dev
        working_dir: /var/www/ecommerce
        volumes:
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - ./:/var/www/ecommerce
        networks:
            - app-network

    ## Nginx Service
    webserver:
        image: nginx:alpine
        container_name: webserver
        restart: always
        tty: true
        ports:
            - 80:80
            - 443:443
        volumes:
            - ./docker/nginx/conf.d:/etc/nginx/conf.d/
            - ./:/var/www/ecommerce
        networks:
            - app-network

    ## Mysql
    mysql:
        platform: linux/x86_64
        image: mysql:8
        container_name: mysql
        restart: always
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel_dev
        cap_add:
            - SYS_NICE
        ports:
            - 3306:3306
        volumes:
            - ./docker/mysql/data:/var/lib/mysql
            - ./docker/mysql/initial-database/init.sql:/docker-entrypoint-initdb.d/init.sql
            - ./docker/mysql/config/my.cnf:/etc/mysql/conf.d/my.cnf
            - ./docker/mysql/logs:/var/log/mysql
        networks:
            - app-network


## Docker Networks
networks:
    app-network:
        driver: bridge
